---
- name: ensure destination for caddyfile file exists
  file:
    path: "{{ caddyfile_path }}"
    state: directory

- name: write caddyfile file
  template:
    src: ../templates/Caddyfile.j2
    dest: "{{ caddyfile_path }}/Caddyfile"
  notify: restart caddy